name: Deploy to Maven Central (Gradle)

on:
  push:
    branches:
      - release
      - snapshot

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Configure Gradle properties
        run: |
          mkdir -p ~/.gradle
          cat << EOF > ~/.gradle/gradle.properties
          mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}
          mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing.gnupg.keyName=${{ secrets.GPG_KEY_ID }}
          signing.gnupg.passphrase=${{ secrets.GPG_PASSPHRASE }}
          EOF

      - name: Modify version for release
        if: github.ref == 'refs/heads/release'
        run: |
          find . -name "build.gradle" -type f -exec sed -i "s/\(def apiVersion = '[^']*\)-SNAPSHOT'/\1'/" {} +

      - name: Modify version for snapshot
        if: github.ref == 'refs/heads/snapshot'
        run: |
          find . -name "build.gradle" -type f -exec sed -i "/-SNAPSHOT'/! s/\(def apiVersion = '[^']*\)'/\1-SNAPSHOT'/" {} +

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and deploy release
        if: github.ref == 'refs/heads/release'
        run: ./gradlew clean publish -PisRelease=true

      - name: Build and deploy snapshot
        if: github.ref == 'refs/heads/snapshot'
        run: ./gradlew clean publish -PisRelease=false